run_and_delete:
	sudo docker run -it --rm --env USER=root slerest/arch/rust /bin/zsh
run:
	sudo docker run -it --env USER=root slerest/arch/rust /bin/zsh
build:
	sudo docker build -t slerest/arch/rust .
